# Generated by Django 2.0.3 on 2018-04-10 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='privacy_level',
            field=models.CharField(choices=[('all', 'Public'), ('friends', 'Friends only'), ('only_me', 'Only me')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
