# Generated by Django 2.0.3 on 2018-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_auto_20180410_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('run', 'user')},
        ),
    ]
