# Generated by Django 2.0.3 on 2018-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0003_auto_20180410_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='max_tempo',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='min_tempo',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
