# Generated by Django 2.0.3 on 2018-04-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0004_auto_20180410_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('num_seconds', models.PositiveIntegerField()),
                ('latitude', models.CharField(max_length=9)),
                ('longitude', models.CharField(max_length=10)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.Participation')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='runners',
            field=models.ManyToManyField(through='REST.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
