# Generated by Django 2.0.3 on 2018-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0005_auto_20180415_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='num_seconds',
        ),
        migrations.AddField(
            model_name='split',
            name='start_time',
            field=models.DateTimeField(default="2017-12-12T12:12+0100"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participation',
            name='max_tempo',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='min_tempo',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
