# Generated by Django 2.0.3 on 2018-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_auto_20180415_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='start_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='split',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='split',
            name='longitude',
        ),
    ]
