# Generated by Django 2.0.3 on 2018-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0007_auto_20180418_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='calories',
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
