# Generated by Django 2.0.3 on 2018-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0009_participation_avg_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
