# Generated by Django 2.0.3 on 2018-04-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0010_auto_20180427_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
