# Generated by Django 2.0.3 on 2018-04-27 22:30

import REST.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0011_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', REST.models.UserManager()),
            ],
        ),
    ]
